### ISSUE TITLE
最后这样运行 sudo docker compose run -itd mirai 这个命令后 就算部署成功了吗》后面还要做什么吗?我向目标QQ发送消息没有反应。。救QAQ

### ISSUE THREAD

**Issue by Oops-re** [mikumifa/QChatGPT-Docker-Installer#7]

**Comment by mikumifa** [comment]
i启动mirai容器
docker compose run -itd mirai
此命令将在后台启动mirai容器

启动主程序容器
docker compose run -itd setup

**Comment by Oops-re** [comment]
运行这两个命令了

**Comment by Oops-re** [comment]
![image](https://user-images.githubusercontent.com/85559748/215314047-fc6ab55d-e726-4ba6-b7e8-c8e75678de24.png)

**Comment by Oops-re** [comment]
![image](https://user-images.githubusercontent.com/85559748/215314087-9508b0a8-a7e6-4190-85c3-d9638f008974.png)

**Comment by mikumifa** [comment]
docker contain logs <那长长的代码> 看一下日志

**Comment by Oops-re** [comment]
![image](https://user-images.githubusercontent.com/85559748/215314245-6d13e01f-9dc1-4eaa-87b1-66587b3728f0.png)

**Comment by Oops-re** [comment]
lighthouse@VM-24-8-ubuntu:~/QChatGPT-Docker-Installer$ sudo docker logs eb53380d4fa816b5351b98ceda21a92c65057b553c829826944f10441fffd069
  08:15:09 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  08:15:09 [INFO] Runtime: OpenJDK 64-Bit Server VM 17-ea (arch: 64)
  08:15:09 [INFO] https://github.com/iTXTech/mirai-console-loader
  08:15:09 [INFO] This program is licensed under GNU AGPL v3
  08:15:09 [INFO] Package "net.mamoe:mirai-api-http" has been updated.
  08:15:10 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  08:15:10 [INFO] Runtime: OpenJDK 64-Bit Server VM 17-ea (arch: 64)
  08:15:10 [INFO] https://github.com/iTXTech/mirai-console-loader
  08:15:10 [INFO] This program is licensed under GNU AGPL v3
  08:15:11 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  08:15:11 [INFO] Verifying "net.mamoe:mirai-console" v2.13.4
  08:15:12 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.4
  08:15:12 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.4
  08:15:12 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  08:15:13 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  08:15:13 [INFO] Verifying "net.mamoe:mirai-api-http" v2.6.2
2023-01-29 08:15:14 I/main: Starting mirai-console...
2023-01-29 08:15:14 I/main: 

==================================[ Mirai consosle 2.13.4 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-01-29 08:15:14 I/main: Backend: version 2.13.4, built on 2023-01-21 13:19:40.
2023-01-29 08:15:14 I/main: Frontend Terminal: version 2.13.4, provided by Mamoe Technologies
2023-01-29 08:15:14 I/main: Welcome to visit https://mirai.mamoe.net/
2023-01-29 08:15:14 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2023-01-29 08:15:14 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2023-01-29 08:15:14 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-01-29 08:15:15 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.6.2
2023-01-29 08:15:15 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-01-29 08:15:15 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-01-29 08:15:15 I/Mirai HTTP API: ********************************************************
2023-01-29 08:15:15 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2023-01-29 08:15:15 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2023-01-29 08:15:15 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-01-29 08:15:15 E/net.mamoe.mirai-api-http: kotlinx.coroutines.JobCancellationException: LazyStandaloneCoroutine is cancelling; job=LazyStandaloneCoroutine{Cancelling}@491f8831
kotlinx.coroutines.JobCancellationException: LazyStandaloneCoroutine is cancelling; job=LazyStandaloneCoroutine{Cancelling}@491f8831
Caused by: java.net.BindException: Address in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:552)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:336)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.network.sockets.ConnectUtilsJvmKt.bind(ConnectUtilsJvm.kt:32)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:46)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:30)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind$default(TcpSocketBuilder.kt:26)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.server.cio.backend.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:46)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-01-29 08:15:15 E/MahKtorAdapter[ws]: java.net.BindException: Address in use
java.net.BindException: Address in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:552)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:336)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.network.sockets.ConnectUtilsJvmKt.bind(ConnectUtilsJvm.kt:32)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:46)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind(TcpSocketBuilder.kt:30)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.network.sockets.TcpSocketBuilder.bind$default(TcpSocketBuilder.kt:26)
        at mirai-api-http-2.6.2.mirai2.jar[shared]//io.ktor.server.cio.backend.HttpServerKt$httpServer$acceptJob$1.invokeSuspend(HttpServer.kt:46)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-01-29 08:15:15 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-01-29 08:15:15 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-01-29 08:15:16 I/main: 1 plugin(s) enabled.
2023-01-29 08:15:16 I/main: mirai-console started successfully.

**Comment by Oops-re** [comment]
是这个 Address in use 这个报错吗？

**Comment by mikumifa** [comment]
配置自动登录了吗

**Comment by Oops-re** [comment]
就是autologin嘛 照着配了 机器人的QQ 密码 还有setConfig

**Comment by mikumifa** [comment]
检查一下，或者重新配置，你的qq mirai机器人没有登录成功

**Comment by Oops-re** [comment]
嗷嗷 行 谢谢大大Orz

**Comment by Oops-re** [comment]
再问一下怎么算登录成功捏？

**Comment by mikumifa** [comment]
日志上面会写，成功登录的（英文），然后会显示你的qq号

**Comment by Funny-dot** [comment]
我的状况跟你一一样的，qq登陆成功了的。dan's但是还是运行不了

![image](https://user-images.githubusercontent.com/27287970/217411968-803fc09d-7c15-48df-9172-d0bcea2cebae.png)

**Comment by Oops-re** [comment]
我也没解决...但是我的18元试用没了。。。摆了
&nbsp;


，，，，
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月8日(星期三) 上午10:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mikumifa/QChatGPT-Docker-Installer] 最后这样运行 sudo docker compose run -itd mirai 这个命令后 就算部署成功了吗》后面还要做什么吗?我向目标QQ发送消息没有反应。。救QAQ (Issue #7)





 
我的状况跟你一一样的，qq登陆成功了的。dan's但是还是运行不了

**Comment by Ryushane** [comment]
同登陆成功，但是bot并没有正确工作...
<img width="940" alt="chatbot_Snipaste_2023-02-08_22-16-08" src="https://user-images.githubusercontent.com/48601190/217554864-081fe301-0d8e-415c-bd10-a37f700ca6ff.png">
